laravel/breeze

stubs/tests/Feature/AuthenticationTest.php
=> [1.x] Fix AuthenticationTest

stubs/resources/views/auth/register.blade.php, stubs/resources/views/auth/reset-password.blade.php
This adds a link so that those who have registered can login directly, like in jetstream
=> [1.x] Add link Already Registered

stubs/resources/views/layouts/navigation.blade.php
=> new value attribute assignement - 1.x -> 1.x

stubs/resources/views/auth/confirm-password.blade.php
Minor, just assuring the message to be translation ready by default
=> [1.x] Allow the message to be translated

stubs/App/Http/Controllers/Auth/RegisteredUserController.php
This PR fixes RegisteredUserController@store docblock
It changes:
~~~php
@param  \App\Http\Requests\LoginRequest  $request
~~~
To
~~~
@param  \Illuminate\Http\Request  $request
~~~
=> Fix RegisteredUserController@store docblock

stubs/resources/views/auth/reset-password.blade.php
Labels can be replaced by x-label component.
=> [1.x] Reuse blade component

src/Console/InstallCommand.php
Removed the PostCSS 7 compat stuffs too
=> [1.x] Upgrade to PostCSS 8 as laravel-mix 6 is out

stubs/resources/views/auth/login.blade.php, stubs/resources/views/auth/verify-email.blade.php, stubs/resources/views/layouts/navigation.blade.php
http://notaverb.com/logout
http://notaverb.com/login
See also: https://github.com/laravel/laravel/pull/5536
=> Change "Logout" text to "Log out" and "Login" to "Log in"

src/Console/InstallCommand.php
Fixes installInertiaStack function to reference stubs/inertia app folder as lowercase.
=> Update stubs/inertia/app case in installInertiaStack

stubs/inertia/resources/js/Pages/Auth/Register.vue
BreezeCheckbox is registered but not used.
=> Remove unused component

composer.json, stubs/default/App/Http/Controllers/Auth/NewPasswordController.php, stubs/default/App/Http/Controllers/Auth/RegisteredUserController.php, stubs/inertia/app/Http/Controllers/Auth/NewPasswordController.php, stubs/inertia/app/Http/Controllers/Auth/RegisteredUserController.php
This pull request makes breeze to use the password rule by default.
=> [1.x] Uses password rule by default

stubs/inertia/app/Http/Controllers/Auth/AuthenticatedSessionController.php
The return docblock is wrong in the Inertia `AuthenticatedSessionController@create` method. This fixes that. 👍
=> Fix create method docblock return value

composer.json, stubs/default/App/Http/Controllers/Auth/NewPasswordController.php, stubs/default/App/Http/Controllers/Auth/RegisteredUserController.php, stubs/inertia/app/Http/Controllers/Auth/NewPasswordController.php, stubs/inertia/app/Http/Controllers/Auth/RegisteredUserController.php
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> Use new `Password::defaults()` feature.

stubs/inertia-react/resources/js/Pages/Welcome.js, stubs/inertia-vue/resources/js/Pages/Welcome.vue
=> Use dashboard named routes

src/Console/InstallCommand.php
Enables installation in PHP 8 projects.
=> Change minimum Sanctum version to 2.8

src/Console/InstallsInertiaStacks.php
=> update `InitialVueStack` packages to latest

src/Console/InstallsBladeStack.php
=> update `BladeStack` dependencies

README.md
=> [1.x]: redirect to breeze 9.x instead of 8.x

src/Console/InstallsInertiaStacks.php, stubs/inertia-common/webpack.config.js, stubs/inertia-common/webpack.mix.js
Same approach from https://github.com/laravel/jetstream/pull/1009.
=> Use `.alias` method from `Mix`

src/Console/InstallCommand.php, src/Console/InstallsInertiaStacks.php, stubs/inertia-common/app/Http/Middleware/HandleInertiaRequests.php, stubs/inertia-common/resources/views/app.blade.php, stubs/inertia-react/resources/js/ssr.js, stubs/inertia-react/webpack.ssr.mix.js, stubs/inertia-vue/resources/js/ssr.js, stubs/inertia-vue/webpack.ssr.mix.js
Same exact approach from https://github.com/laravel/jetstream/pull/1012
Beside Vue, we also got React working with SSR.
PS: Also updated the node dependencies.
=> [1.x] Add Inertia SSR Support 

stubs/inertia-react/resources/js/Components/Input.js, stubs/inertia-react/resources/js/Pages/Auth/Login.js, stubs/inertia-react/resources/js/Pages/Auth/Register.js, stubs/inertia-react/resources/js/Pages/Auth/ResetPassword.js
=> add id to Input component

stubs/inertia-common/app/Http/Middleware/HandleInertiaRequests.php, stubs/inertia-react/resources/js/ssr.jsx, stubs/inertia-vue/resources/js/ssr.js
See: https://github.com/laravel/jetstream/pull/1078
=> [1.x] Fix ziggy determing current URL when using SSR

composer.json, src/Console/InstallsApiStack.php, src/Console/InstallsBladeStack.php, src/Console/InstallsInertiaStacks.php
This pull request improves the console output of Breeze.
=> [1.x] Improves console output

src/Console/InstallsInertiaStacks.php
=> [1.x] Bump React and Vue Dependencies

composer.json, src/Console/InstallsInertiaStacks.php, stubs/inertia-common/resources/views/app.blade.php
Depends on: https://github.com/laravel/framework/pull/44096
=> [1.x] Vite preloading

stubs/default/resources/views/layouts/navigation.blade.php
=> Fix closing tag

.gitignore, stubs/default/resources/views/auth/confirm-password.blade.php, stubs/default/resources/views/auth/forgot-password.blade.php, stubs/default/resources/views/auth/login.blade.php, stubs/default/resources/views/auth/register.blade.php, stubs/default/resources/views/auth/reset-password.blade.php, stubs/default/resources/views/auth/verify-email.blade.php, stubs/default/resources/views/components/auth-card.blade.php, stubs/default/resources/views/layouts/guest.blade.php
Moved duplicated logo component to guest layout
=> [1.x] Blade stack - Moved duplicated logo component to guest layout

stubs/default/app/Http/Controllers/Auth/PasswordController.php, stubs/default/app/Http/Controllers/ProfileController.php, stubs/default/app/Http/Requests/ProfileUpdateRequest.php, stubs/default/tests/Feature/Auth/PasswordUpdateTest.php, stubs/default/tests/Feature/ProfileTest.php, stubs/inertia-common/app/Http/Controllers/Auth/PasswordController.php, stubs/inertia-common/app/Http/Controllers/ProfileController.php, stubs/inertia-common/tests/Feature/Auth/PasswordUpdateTest.php, stubs/inertia-common/tests/Feature/ProfileTest.php
This pull request adds types to profile feature that was missing types.
=> [feat/types] Adds types to profile page related features

src/Console/InstallCommand.php, src/Console/InstallsApiStack.php, src/Console/InstallsBladeStack.php, src/Console/InstallsInertiaStacks.php
This pull request allows the installation of `--pest` on Laravel 10.
=> [1.x] Allows to install `--pest` in Laravel 10

stubs/default/routes/web.php
=> [1.x] Laravel 10.x adjust wording

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist
This pull request adds type checking to this repository.
=> [1.x] Adds type checking

stubs/inertia-common/pest-tests/Feature/Auth/PasswordUpdateTest.php
Inertia password update feature tests.
The phpunit test stub is fine.
The pest test stub has wrong endpoints.
=> Fix password-update pest tests

.github/workflows/tests.yml, composer.json, src/Console/InstallCommand.php, stubs/default/pest-tests/Feature/ExampleTest.php, stubs/default/pest-tests/Unit/ExampleTest.php
This pull request makes the Breeze installer use Pest 2.
=> [1.x] Uses Pest 2

src/Console/InstallCommand.php
=> [1.x] Highlight Alpine

stubs/api/pest-tests/Feature/Auth/AuthenticationTest.php, stubs/api/tests/Feature/Auth/AuthenticationTest.php, stubs/default/pest-tests/Feature/Auth/AuthenticationTest.php, stubs/default/tests/Feature/Auth/AuthenticationTest.php
This PR adds the missing **logout** tests.
=> [1.x] Add logout tests.

src/Console/InstallsBladeStack.php, src/Console/InstallsInertiaStacks.php, src/Console/InstallsLivewireStack.php
Please see [PostCSS line return parsing error vulnerability](https://github.com/advisories/GHSA-7fh5-64p2-3v2j)
=> Update PostCSS version

src/Console/InstallsInertiaStacks.php
=> [1.x] Vite 5

stubs/inertia-react-ts/resources/js/Pages/Welcome.tsx, stubs/inertia-react/resources/js/Pages/Auth/Login.jsx, stubs/inertia-react/resources/js/Pages/Auth/ResetPassword.jsx, stubs/inertia-react/resources/js/Pages/Welcome.jsx, stubs/inertia-vue-ts/resources/js/Pages/Welcome.vue, stubs/inertia-vue/resources/js/Pages/Welcome.vue, stubs/livewire-common/resources/views/welcome.blade.php, stubs/livewire-functional/resources/views/livewire/welcome/navigation.blade.php, stubs/livewire/resources/views/livewire/welcome/navigation.blade.php
Pairs with https://github.com/laravel/laravel/pull/6335
I think I got all the different versions working correctly 😅
=> Implement 11.x welcome page design
