stubs/resources/views/auth/login.blade.php

Minor, but the email label is duplicated. This updates the label for the password input correctly.

Update password label

---

README.md

This pull request makes Breeze a `--dev` dependency, so people don't end up with this dependency in production.

Makes breeze a --dev dependency

---

src/Console/InstallCommand.php
stubs/resources/js/app.js
stubs/resources/views/layouts/app.blade.php
stubs/resources/views/layouts/guest.blade.php

This PR. allow to use `alpinejs` locally from `npm` instead of import CDN link.

install alpinejs via npm instead of cdn import

---

stubs/App/Http/Controllers/Auth/PasswordResetLinkController.php
stubs/resources/views/auth/forgot-password.blade.php
stubs/resources/views/auth/login.blade.php
stubs/resources/views/auth/register.blade.php
stubs/resources/views/auth/reset-password.blade.php

When redirecting the user back after a failed validation (while attempting to register, sign in, or resetting the password), the `name` and `email` fields are now filled with the old values.

Restoring old input values after a failed validation

---

stubs/resources/views/auth/forgot-password.blade.php
stubs/resources/views/auth/login.blade.php
stubs/resources/views/auth/register.blade.php
stubs/resources/views/auth/reset-password.blade.php

`{{ }}` syntax isn't supported on Blade components. 
Fixes https://github.com/laravel/breeze/pull/9

[1.x] Fix old value attribute assignement

---

stubs/routes/auth.php

This removes the middleware array syntax for routes with only one middleware. It also reorders the middleware and name declaration of the logout route to be the same as the other routes.

[1.x] Auth routes consistency

---

stubs/App/Http/Controllers/Auth/AuthenticatedSessionController.php
stubs/App/Http/Controllers/Auth/ConfirmablePasswordController.php

Just some very minor changes to make the package more SPA compatible out the box:
1. Be explicit with the authentication guard otherwise a SPA will attempt to use the `RequestGuard` and fail.
2. Throw a `ValidationException` if the confirmed password is invalid.
There's of course many ways to implement both points, I've gone with the least amount of change, however:
1. We could type hint the `StatefulGuard` in the constructor like Fortify's [AuthenticatedSessionController](https://github.com/laravel/fortify/blob/1.x/src/Http/Controllers/AuthenticatedSessionController.php#L35) and [ConfirmablePasswordController](https://github.com/laravel/fortify/blob/1.x/src/Http/Controllers/ConfirmablePasswordController.php#L28).
2. We could wrap the exception in an `if ($request->wantsJson()) {` …

[1.x] Improve SPA compatibility

---

stubs/App/Http/Controllers/Auth/AuthenticatedSessionController.php

Had some users complaining that email verification was not working properly in some cases.
For example on ios, when a user clicks the verification link, link is opened in a new window without any sessions.
The `auth` middleware will now prevent the email verification process since the user is not logged in.
This minor fix ensures a redirect to the intended page after login. In this example, back to verification link after login, which works fine now.
Without this fix users would be redirected to the `/verify-mail` page after login (depending on the `verified` middleware), with the option to resend the verification mail. This process will then be repeated over and over.
This should also fix the situation registration on device A, validation on device B (which has no active session)

[1.x] Redirect to intended path after login

---

src/Console/InstallCommand.php

Fix a small typo:
- `stubs/default/webpack.config.js` does not exists
- `stubs/inertia/webpack.config.js` exists but was not copied

Copy webpack.config.js on inertia init

---

src/Console/InstallCommand.php
stubs/inertia/resources/js/app.js

This PR adds Inertia Progress to the base scaffold and uses the Laravel orange hex #F05340 for the progress bar.

Add @inertiajs/progress to package dependencies

---

src/Console/InstallCommand.php

This fixes a bug introduced in #46, which is currently causing the `php artisan breeze:install --inertia` call to fail:
```
✝ ~/Code/claudiodekker/test-breeze  master±  php artisan breeze:install --inertia
ParseError
syntax error, unexpected ':', expecting ']'
at /Users/claudiodekker/Code/claudiodekker/breeze/src/Console/InstallCommand.php:111
107▕         $this->updateNodePackages(function ($packages) {
108▕             return [
109▕                 '@inertiajs/inertia' => '^0.8.4',
110▕                 '@inertiajs/inertia-vue3' => '^0.3.5',
➜ 111▕                 '@inertiajs/progress': '^0.2.4',
112▕                 '@tailwindcss/forms' => '^0.2.1',
```

[1.x] Fix unexpected ':' in key-value array

---

stubs/inertia/resources/js/app.js

I just came here to add the Inertia progress bar, and was happy to see that @ninjaparade beat me to it! 😍
That said, I think it might be better to leave the `delay`, `includeCSS` and `showSpinner` out, and let them fallback to the defaults. Most projects don't need to touch those settings, IMHO.

[1.x] Simplify Inertia progress

---

stubs/inertia/resources/js/Pages/Auth/Login.vue

Added errors and auth props to get rid of this Vue warning: [Vue warn]: Extraneous non-props attributes (errors, auth) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. See: https://inertiajs.com/validation#displaying-errors. I guess this error is caused by a layout feature/bug in Inertia, so it might be solved by Inertiajs in the future.

Fixes Vue warning

---

stubs/default/App/Http/Controllers/Auth/EmailVerificationNotificationController.php

Updating the return type in `EmailVerificationNotificationController` to `\Illuminate\Http\RedirectResponse` after receiving the following errors from phpstan:
```
vendor/bin/phpstan analyse --memory-limit 4G -c phpstan.neon app tests
43/43 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Line   app/Http/Controllers/Auth/EmailVerificationNotificationController.php
------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
19     Method App\Http\Controllers\Auth\EmailVerificationNotificationController::store() …
```

Fix return type for phpstan

---

stubs/default/App/Http/Controllers/Auth/RegisteredUserController.php
stubs/inertia/app/Http/Controllers/Auth/RegisteredUserController.php

This fixes the wrong order of events firing on user registration. It was caused by the Auth::login() happening before firing the Registered event.
Order before: Login event, then Register event.  
Order now: Register event, then Login event.
This could have possibly caused confusion and problems for apps that rely on the events firing in the correct order, which is the same as what happens in reality: user is first registered, and only then can the user login.

Fix Login event firing before Register

---

stubs/inertia/resources/js/Pages/Auth/ConfirmPassword.vue
stubs/inertia/resources/js/Pages/Auth/ForgotPassword.vue
stubs/inertia/resources/js/Pages/Auth/Register.vue
stubs/inertia/resources/js/Pages/Auth/ResetPassword.vue
stubs/inertia/resources/js/Pages/Auth/VerifyEmail.vue
stubs/inertia/resources/js/Pages/Dashboard.vue
stubs/inertia/resources/js/Pages/Welcome.vue

When visiting forgot-password page there is a console [Vue warn]: Extraneous non-props attributes (errors, auth) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
The reason is [Attribute Inheritance on Multiple Root Nodes](https://v3.vuejs.org/guide/component-attrs.html#attribute-inheritance-on-multiple-root-nodes)
Inertia shares `errors` as a prop by default and Breeze shares `auth` as a prop by default. If those props are not explicitly defined on each page component a Vue runtime warning will be issued.
We can wrap all the root nodes of the page component in a `<div>` to create a single root component and get rid of the warning, But those props will be inherited as [Non-Prop …

Fix Vue warning

---

src/Console/InstallCommand.php
stubs/inertia/jsconfig.json

This PR adds a `jsconfig.json` file to the Inertia scaffolding to allow javascript services in VSCode to allow better support for the `@` alias. 
More information about the `jsconfig.json` file can be read (here)[https://code.visualstudio.com/docs/languages/jsconfig]

[1.x] Add `jsconfig.js`

---

src/Console/InstallCommand.php

Currently you can not install Breeze along side Spark due to version conflicts. 
Spark requires `^0.4.1` where as Breeze is at `^0.3.5`

[1.x] Bump Inertia version to match Spark

---

stubs/inertia-common/resources/views/app.blade.php

this pull request reflects the same change that has jetstream on inertia stack that is already merged <a target="_blank" href="https://github.com/laravel/jetstream/pull/797">fix cors policy errors with inertia stack #797</a>
<hr/>
on inertia stack a when you run `npm install && npm run watch` if you work with `.test` domains like Laravel Valet add, the watcher does not add live reload with `browserSync` you must work with `localhost` ip to work with vue components.
to avoid this by adding this tag on `app.blade.php` file on inertia stack it would reload `.test` domains as it is a `localhost` domain.
it avoid confusion on why vue components does not reload using browserSync by default, and make easier the workflow with inertia and of course with jetstream.

[1.x] Fix CORS policy errors with inertia stack

---

src/Console/InstallCommand.php

Just a little fix to replace .vue to .js in tailwind purge configuration.

fix purge line to include *.js

---

stubs/inertia-vue/resources/js/Components/Dropdown.vue
stubs/inertia-vue/resources/js/Components/ValidationErrors.vue
stubs/inertia-vue/resources/js/Layouts/Authenticated.vue
stubs/inertia-vue/resources/js/Layouts/Guest.vue
stubs/inertia-vue/resources/js/Pages/Auth/ConfirmPassword.vue
stubs/inertia-vue/resources/js/Pages/Auth/ForgotPassword.vue
stubs/inertia-vue/resources/js/Pages/Auth/Login.vue
stubs/inertia-vue/resources/js/Pages/Auth/Register.vue
stubs/inertia-vue/resources/js/Pages/Auth/ResetPassword.vue
stubs/inertia-vue/resources/js/Pages/Auth/VerifyEmail.vue
stubs/inertia-vue/resources/js/Pages/Dashboard.vue
stubs/inertia-vue/resources/js/app.js

This PR adds the `.vue` extension to all Breeze Vue imports.
This will become useful when someone want to switch from Laravel Mix to ViteJS because Vite does not support extension-less Vue imports. You can take a look here (https://github.com/vitejs/vite/issues/178#issuecomment-630138450)

Add Vue file extension to all Vue components imported

---

stubs/inertia-react/resources/js/Layouts/Authenticated.js

The responsive (mobile) link to the Dashboard, has the wrong method applied to the link, to a route that does not exist by default (POST on /dashboard). This PR simply changes the link to be in line with the one show on the desktop version.

Fix - Change from POST to GET on responsive dashboard link

---

stubs/inertia-react/resources/js/Components/Dropdown.js

The previous commit fixed `InertiaLink` to `Link` which now created an error when running `npm run dev`. This commit fixes "Identifier 'Link' has already been declared" error.

Fix React Dropdown.js Link

---

README.md

Seems like Breeze is one of the only packages that doesn't yet have the same link as the rest of our packages.

[1.x] Replace docs with link to actual docs

---

src/Console/InstallCommand.php

This pull request addresses an issue where the option `--pest` was being ignored when the user selected vue or react.

[1.x] Fixes installation of pest on vue/react stacks

---

src/Console/InstallCommand.php
stubs/default/resources/js/app.js
stubs/default/resources/views/components/dropdown.blade.php

Upgrade alpinejs version from v2 to v3
Change app.js to call alpinejs, source [https://alpinejs.dev/essentials/installation#as-a-module](https://alpinejs.dev/essentials/installation#as-a-module)
Rename `@click.away` to `@click.outside`, source [https://alpinejs.dev/upgrade-guide#away-replace-with-outside](https://alpinejs.dev/upgrade-guide#away-replace-with-outside)

upgrade alpinejs to v3

---

stubs/inertia-vue/resources/js/Components/Dropdown.vue

Use KeyboardEvent `key` attribute for Escape instead of deprecated `keyCode`.
See https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Use KeyboardEvent `key` attribute for Escape

---

.github/workflows/update-changelog.md

Trying out the auto updater for a Changelog by @stefanzweifel on Breeze. If this goes well, I'll roll this out to every repo.
Could potentially save me quite a bit of time while doing release 🤞

Auto update changelog on release

---

stubs/inertia-common/app/Http/Controllers/Auth/ConfirmablePasswordController.php
stubs/inertia-common/app/Http/Controllers/Auth/EmailVerificationNotificationController.php
stubs/inertia-common/app/Http/Controllers/Auth/NewPasswordController.php
stubs/inertia-common/app/Http/Controllers/Auth/PasswordResetLinkController.php
stubs/inertia-common/app/Http/Controllers/Auth/RegisteredUserController.php
stubs/inertia-vue/resources/js/Components/Input.vue

- Fix correct @return tag for Inertia response
- Fix Inertia vue Input component autofocus. The method `focus()` doesn't work. With this change the method is called if input has attribute "autofocus" on mounted.

Fix Inertia Controllers @return tag and Inertia Vue Input Component

---

src/Console/InstallsInertiaStacks.php

I noticed there was a couple of things not working, and then i realized it was an outdated dependencies issue. Turns out a lot of the dependencies for React Stack was outdated, which is funny because the same doesn't occur for the Vue one. I don't really like vue myself so i stick to react.

update outdated dependencies for react stack

---

stubs/inertia-react/resources/js/Components/Label.js

```js
<Label htmlFor="current_password">
Current Password
</Label>
```
And you'll get an error like so `Uncaught Error: Objects are not valid as a React child (found: object with keys {children})`
But if you remove the brackets before the children, it'll gone.
```js
// Before
{value ? value : { children }}
// After
{value ? value : children}
```
Now, we can use `Label` either with `children` or `forInput` props.

Remove brackets on react label component

---

stubs/api/App/Http/Controllers/Auth/EmailVerificationNotificationController.php
stubs/api/App/Http/Controllers/Auth/NewPasswordController.php
stubs/api/App/Http/Controllers/Auth/PasswordResetLinkController.php
stubs/api/App/Http/Middleware/EnsureEmailIsVerified.php

This pull request fixes the DocBlocks `@return` tag for API scaffolding
- Use `JsonResponse` instated of `RedirectResponse`

Fix API Controllers @return tag

---

stubs/api/App/Http/Controllers/Auth/NewPasswordController.php
stubs/api/App/Http/Controllers/Auth/PasswordResetLinkController.php

#109 introduced some exception throwing with ternary expressions. However, this is only available as of PHP 8 and Breeze still supports PHP 7.3 and 7.4.

[1.x] Fix exception throwing on older PHP versions

---

stubs/api/tests/Feature/EmailVerificationTest.php

fixed the EmailVerificationTest.php
```diff
-$response->assertRedirect(RouteServiceProvider::HOME.'?verified=1');
+$response->assertRedirect(config('app.frontend_url').RouteServiceProvider::HOME.'?verified=1');
```

FIX: Api stack EmailVerificationTest assertRedirect

---

.github/workflows/update-changelog.yml

This PR fixes the `update-changelog.yml` workflow to push the changed workflow to the repositories default branch.
Previously the workflow used `${{ github.ref_name }}` which evaluates to the tag name (`v1.0.0`). This doesn't work as `v1.0.0` is not an actual branch in the repository.
We are now using `${{ github.event.repository.default_branch }}` which evaluates to `1.x`. 
This should resolve the issue Dires mentioned in https://github.com/laravel/breeze/pull/113#issuecomment-1021539840.
I've successfully tested this in a test repository:
- [Workflow File](https://github.com/stefanzweifel/git-auto-commit-action-non-default-branch/actions/runs/1749707173/workflow)
- [Workflow run](https://github.com/stefanzweifel/git-auto-commit-action-non-default-branch/runs/4948435325?check_suite_focus= …

[1.x] Push updated Changelog to default branch

---

.github/workflows/update-changelog.yml

Use the target branch of a release in the compare URL when updating the changelog through GitHub Actions.

[1.x] Use release target branch in changelog compare URL

---

src/Console/InstallsInertiaStacks.php
stubs/inertia-vue/resources/js/Components/Button.vue
stubs/inertia-vue/resources/js/Components/Checkbox.vue
stubs/inertia-vue/resources/js/Components/Dropdown.vue
stubs/inertia-vue/resources/js/Components/DropdownLink.vue
stubs/inertia-vue/resources/js/Components/Input.vue
stubs/inertia-vue/resources/js/Components/InputError.vue
stubs/inertia-vue/resources/js/Components/Label.vue
stubs/inertia-vue/resources/js/Components/NavLink.vue
stubs/inertia-vue/resources/js/Components/ResponsiveNavLink.vue
stubs/inertia-vue/resources/js/Components/ValidationErrors.vue
stubs/inertia-vue/resources/js/Layouts/Authenticated.vue
stubs/inertia-vue/resources/js/Layouts/Guest.vue
stubs/inertia-vue/resources/js/Pages/Auth/ConfirmPassword.vue
stubs/inertia-vue/resources/js/Pages/Auth/ForgotPassword.vue
stubs/inertia-vue/resources/js/Pages/Auth/Login.vue
stubs/inertia-vue/resources/js/Pages/Auth/Register.vue
stubs/inertia-vue/resources/js/Pages/Auth/ResetPassword.vue
stubs/inertia-vue/resources/js/Pages/Auth/VerifyEmail.vue
stubs/inertia-vue/resources/js/Pages/Dashboard.vue
stubs/inertia-vue/resources/js/Pages/Welcome.vue

This PR transitions the Inertia Vue 3 stubs to use Vue's `<script setup>` syntax.
The [official Vue docs](https://vuejs.org/api/sfc-script-setup.html) recommend using the `<script setup>` syntax when using the Composition API with Single File Components as it reduces boilerplate and increases performance. It also significantly improves working with TypeScript, for users who may wish to convert their Breeze installation.
The PR also moves the `<script setup>` section to the top of the single file components to be consistent with the Vue docs and Evan's recommendations.
Note that the semicolons in the current code were applied inconsistently so I have also added them where appropriate. The Vue docs don't use semicolons, however the StyleCI …

Transition Inertia Vue stubs to `<script setup>` syntax

---

stubs/api/pest-tests/Feature/EmailVerificationTest.php

This PR fixes the asserted redirect route in the `EmailVerificationTest` of the `api` stack when using the `--pest` test suite.
This is basically the same like #122 updated for the default phpunit tests.

[1.x] Fix assertRedirect in EmailVerificationTest when using API with pest

---

stubs/default/routes/auth.php

[1.x] Group common middleware instead of duplicating

---

stubs/api/routes/auth.php

- PHP 8.1.2
- Laravel 9.1.0
file: `app/Http/Middleware/Authenticate.php` uses route helper with name `login`
This PR adds the route name `login`
 
```php
<?php
namespace App\Http\Middleware;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
class Authenticate extends Middleware {
/**
* Get the path the user should be redirected to when they are not authenticated.
*
* @param  \Illuminate\Http\Request  $request
* @return string|null
*/
protected function redirectTo($request)
{
if (! $request->expectsJson()) {
return route('login');
}
}
}
```
```sh
laravel new laravel-api
cd laravel-api
php artisan breeze:install api
php artisan migrate
php artisan serve
```

[1.x] add routes name to register and login  paths

---

src/Console/InstallsInertiaStacks.php

I tried to install Laravel breeze with Inertia following [Docs](https://laravel.com/docs/9.x/starter-kits#breeze-and-inertia) but I got following error while installing node packages:
I updated inertia version to latest (0.11.0) as mentioned in [Inertia Releases](https://github.com/inertiajs/inertia/releases) 
After this update, everything worked fine.
I only work with Vue, So I did not updated this version for react because  it may be working fine.

Updated Inertia Version to Latest

---

stubs/inertia-react/resources/js/Components/Dropdown.js

This PR fixes an issue where the content inside a dropdown (e.g. the "Log Out" link) was unable to be clicked in the React version of Breeze.
The "click away" element (used to trigger the closing of the dropdown when clicking away from it) was covering the dropdown menu, so when you think you are clicking the dropdown, you are actually hitting the click-away element, even though the dropdown has a higher z-index.
This is because the Headless UI `Transition` component creates a wrapper div by default. The wrapper div has `transform` and `opacity` properties which create a new z-index [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).
```html
<div class="fixed inset-0 z-40"></div>
<div class="transform opacity-100 …
```

[1.x] Fix inability to click dropdown content in React version

---

stubs/default/tailwind.config.js
stubs/inertia-common/tailwind.config.js

This PR fixes the new TailwindCSS 3.1 First-party TypeScript types feature. 
This Bug was introduced with.
https://github.com/laravel/breeze/pull/156
Thanks to @martinvadel who recognized it.

fix TailwindCSS first party TypeScript types weren't working right

---

stubs/default/vite.config.js
stubs/inertia-react/vite.config.js
stubs/inertia-vue/vite.config.js

This PR makes all the breeze stacks come with the default Laravel watching configuration out of the box.
As it stands, this will perform a full page refresh while running `npm run dev` and saving files within the following directories:
```
resources/views/**
routes/**
```
The configured directories can still be manually configured if needed.
I believe this makes sense in all of these stacks as Inertia AND Ziggy are utilised, so this default refresh config should be a benefit to all the stacks.
Tested stacks:
- Blade
- Vue
- Vue --ssr
- React
- React --ssr
See: https://github.com/laravel/vite-plugin/pull/43

[1.x] Add default view / routes reloading to breeze stacks

---

composer.json

Actually, breeze v1.10.0 also needs this `conflict` rule.

Laravel 8 don't support the vite.

---

src/Console/InstallsInertiaStacks.php

When I installed Breeze (React & SSR) as per this tutorial: https://laravel.com/docs/9.x/starter-kits#laravel-breeze-installation
When running the command `php artisan breeze:install react --ssr`, it returns an error like the following image.
This is because when we unlink the `app.js` file doesn't exist, I added checking for the existence of the file first.

Fix: React SSR installation error

---

src/Console/InstallsInertiaStacks.php

This PR updates the `.gitignore` entry that we add for the SSR build directory to use the new location from https://github.com/laravel/vite-plugin/pull/70.
We should hold off releasing this until the new version of `laravel-vite-plugin` has also been released.

[1.x] Update SSR directory

---

stubs/default/resources/views/layouts/app.blade.php
stubs/default/resources/views/layouts/guest.blade.php
stubs/inertia-common/resources/views/app.blade.php

Similar to https://github.com/laravel/laravel/pull/5952 - a GDPR compliant version can be used for Breeze for default installations.

[1.x] Switch to fonts.bunny.net instead of Google Fonts

---

src/Console/InstallCommand.php

Currently, when running `breeze:install`, if you specify an invalid stack argument, you will get the Blade stack. This is confusing if you typo the stack (e.g. `vu`).
This PR is related to the Jetstream PR at https://github.com/laravel/jetstream/pull/1113, with the main difference being that Breeze has a default argument of "blade" for the `stack` argument.

[1.x] Validate the stack argument

---

src/Console/InstallCommand.php
src/Console/InstallsBladeStack.php
src/Console/InstallsInertiaStacks.php

This PR updates the Breeze installer to automatically run the `npm install` and `npm run build` commands for you. This will make Breeze consistent with this [Jetstream PR](https://github.com/laravel/jetstream/pull/1119).

[1.x] Install NPM dependencies and build assets

---

src/Console/InstallsApiStack.php

At the moment, when email verification is enabled on the API/Next.js stack, the email verification links with the default URI structure (`http://localhost:8000/verify-email/xx/xx?expires=xx&signature=xx`) redirect to `http://locahost:3000/home?verified=1` which does not exist and thus, a 404 page gets rendered.
This MR sets the application home URI to `/dashboard` as a more reasonable default value since the `/home` URI does not exist by default but `/dashboard` exists on the Breeze Next.js example app. Alternatively, this could be set to `/` as this URL should be available on most apps. This then will be used by the `VerifyEmailController` for redirection to `config('app.frontend_url').RouteServiceProvider::HOME.'?verified=1'`.

Set application home URI to /dashboard

---

.github/workflows/tests.yml

This PR adds a `tests` workflow to ensure that the Breeze stacks compile successfully and that the stubbed tests pass.
The workflow is based on the [Jetstream tests workflow](https://github.com/laravel/jetstream/blob/2.x/.github/workflows/tests.yml). The main difference is that I've removed the `test` job because this repository doesn't have any tests (excluding the tests that Breeze scaffolds, which are now tested).

[1.x] Test stubs in CI

---

stubs/default/routes/web.php

The Vue and React stacks have the `verified` middleware on the `/dashboard` route by default:
https://github.com/laravel/breeze/blob/c478aba7fb64b93ae1f7d6ca3f47a9a87f31f8aa/stubs/inertia-common/routes/web.php#L27-L29
This PR updates the Blade stack to be the same. Note that it only takes effect if the `MustVerifyEmail` interface is implemented on the `User` model.
It's obviously a personal preference whether or not the dashboard should require verification, so an alternative would be to remove it from the other stacks. Personally, I like that it's there by default as it's safer and demonstrates a feature that Breeze provides UI components for.

[1.x] Consistently use `verified` middleware on `/dashboard` route.

---

stubs/default/resources/views/layouts/app.blade.php

In the Vue and React stacks, the `header` slot on the authenticated layout is optional:
https://github.com/laravel/breeze/blob/c478aba7fb64b93ae1f7d6ca3f47a9a87f31f8aa/stubs/inertia-vue/resources/js/Layouts/AuthenticatedLayout.vue#L97-L102
https://github.com/laravel/breeze/blob/c478aba7fb64b93ae1f7d6ca3f47a9a87f31f8aa/stubs/inertia-react/resources/js/Layouts/AuthenticatedLayout.jsx#L114-L118
This PR updates the Blade app layout to be the same.

[1.x] Make Blade app header optional

---

stubs/inertia-common/app/Http/Middleware/HandleInertiaRequests.php

This pull request fixes the `HandleInertiaRequests::handle` related types.
Note, the type is mixed[], because array<string, mixed> would be technically incorrect as passing an integer as a key is theoretically supported.

Fixes `HandleInertiaRequests::handle` related types.

---

stubs/inertia-vue/resources/js/Components/Checkbox.vue

All VueJS components use a **single quote (')** for string but in **Checkbox. Vue** Line 22 uses a **double quote(")**
It makes it **inconsistent** with others.

Replace double quote(") with single quote(')

---

src/Console/InstallsInertiaStacks.php
stubs/inertia-common/resources/views/app.blade.php

This ensure the dev server can continue to function after the preloading improvements.

Fix preloading in dev

---

stubs/api/app/Http/Controllers/Auth/RegisteredUserController.php
stubs/default/app/Http/Controllers/Auth/RegisteredUserController.php
stubs/inertia-common/app/Http/Controllers/Auth/RegisteredUserController.php

The validators in `RegisteredUserController` stubs should reference the User model name instead of table name to avoid  error throw when registering a new user and the table name defined in `App\Models\User` consists of `database schema` + `table name`.
**Use case**
Configure the `App\Models\User` class with a not default database schema as table name:
```php
protected $table = "foobar.users";
```
Try to register a new user and then the error occur:
```sql
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "users" does not exist LINE 1: 
select count(*) as aggregate of "users" where "email" = $1
```

RegisteredUserController stubs should use the User model name instead of table name in the validators

---

stubs/inertia-react/resources/js/Pages/Auth/ForgotPassword.jsx
stubs/inertia-react/resources/js/Pages/Auth/Login.jsx
stubs/inertia-react/resources/js/Pages/Auth/Register.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/DeleteUserForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdatePasswordForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx

React formatting

---

stubs/inertia-vue/resources/js/Pages/Profile/Edit.vue

The variable status must be string because in component UpdateProfileInformationForm, status is string.

status must be String

---

stubs/inertia-react/resources/js/Components/ApplicationLogo.jsx
stubs/inertia-react/resources/js/Components/Checkbox.jsx
stubs/inertia-react/resources/js/Components/DangerButton.jsx
stubs/inertia-react/resources/js/Components/Dropdown.jsx
stubs/inertia-react/resources/js/Components/InputLabel.jsx
stubs/inertia-react/resources/js/Components/Modal.jsx
stubs/inertia-react/resources/js/Components/NavLink.jsx
stubs/inertia-react/resources/js/Components/PrimaryButton.jsx
stubs/inertia-react/resources/js/Components/ResponsiveNavLink.jsx
stubs/inertia-react/resources/js/Components/SecondaryButton.jsx
stubs/inertia-react/resources/js/Components/TextInput.jsx
stubs/inertia-react/resources/js/Layouts/AuthenticatedLayout.jsx
stubs/inertia-react/resources/js/Layouts/GuestLayout.jsx
stubs/inertia-react/resources/js/Pages/Auth/ConfirmPassword.jsx
stubs/inertia-react/resources/js/Pages/Auth/ForgotPassword.jsx
stubs/inertia-react/resources/js/Pages/Auth/Login.jsx
stubs/inertia-react/resources/js/Pages/Auth/Register.jsx
stubs/inertia-react/resources/js/Pages/Auth/ResetPassword.jsx
stubs/inertia-react/resources/js/Pages/Auth/VerifyEmail.jsx
stubs/inertia-react/resources/js/Pages/Dashboard.jsx
stubs/inertia-react/resources/js/Pages/Profile/Edit.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/DeleteUserForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdatePasswordForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx
stubs/inertia-react/resources/js/Pages/Welcome.jsx
stubs/inertia-react/resources/js/app.jsx
stubs/inertia-react/resources/js/ssr.jsx
stubs/inertia-react/resources/views/app.blade.php

Hi, I fixed modal closing by adding "show" in useEffect dependency on DeleteUserForm page.
Then I cleaned up React calls that are no longer needed.

Fix close modal with escape keydown and cleanup import react

---

src/Console/InstallsBladeStack.php
src/Console/InstallsInertiaStacks.php

**This PR will fix errors that occur after initial Breeze installation if a User is using an NPM package manager other than NPM itself**
Many people initially start a fresh Laravel project by configuring their database and using their favorite package manager whether that be npm, yarn, or pnpm. The following files that I changed autoloaded the bundling of assets using npm as the default package manager even while a user may be already using pnpm or yarn.  If a user is already using pnpm or yarn they will receive an error in their terminal that looks similar to the following:
```
298 error code EUNSUPPORTEDPROTOCOL
299 error Unsupported URL Type "link:": link:./src/types
300 verbose exit 1
301 timing npm Completed in 14690ms
302 verbose unfinished npm timer reify 1670217709459
303 verbose …
```

Use Default NPM Package Manager of User if Lock File Exists In Base Path

---

stubs/default/resources/views/profile/partials/delete-user-form.blade.php
stubs/inertia-react/resources/js/Pages/Profile/Partials/DeleteUserForm.jsx
stubs/inertia-vue/resources/js/Pages/Profile/Partials/DeleteUserForm.vue

Fixes a typo in the "Delete user" forms.

Fix typo in delete user forms

---

stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdatePasswordForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx

Noticed I was getting warnings in the dev console so I fixed spelling/capitalization of the autoComplete prop within the TextInput.jsx component. Fixed both component references in UpdatePasswordForm.jsx and UpdateProfileInformationForm.jsx. No longer receiving warning in the dev console.

Fixed capitalization of autoComplete prop

---

stubs/inertia-vue/resources/js/Pages/Profile/Partials/DeleteUserForm.vue
stubs/inertia-vue/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue

When running eslint a few errors are presented.
```
resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
7:10  error  'ref' is defined but never used  no-unused-vars
```
```
/resources/js/Pages/Profile/Partials/DeleteUserForm.vue
8:19  error  'usePage' is defined but never used  no-unused-vars
```
I double checked and yeah not used within those components.

Remove unused vue imports

---

src/Console/InstallCommand.php

This PR updates the installer to not have a default stack.
Instead, when the `stack` argument is not provided and the terminal is interactive, the installer will prompt the user:
It will then ask whether they would like to install dark mode, SSR (if applicable), and/or Pest tests. These all default to no.
> **Note** If the user provides the `stack` argument, then it's assumed they know what they want, and the command won't prompt for anything.
When run in non-interactive mode, and no `stack` argument is provided, the command will error:
This change could technically be considered a breaking change, but given Breeze is a single-use package, I don't think it's worth a major version bump.

[1.x] Prompt when the stack argument is not provided

---

src/Console/InstallCommand.php

This PR updates the prompts introduced in #236 to use the Illuminate console components. I'd used them when I took the screenshot for that PR, but forgot to actually commit them :woman_facepalming:

[1.x] Use Illuminate console components for prompting

---

.github/workflows/tests.yml
composer.json
src/Console/InstallCommand.php
src/Console/InstallsInertiaStacks.php

This PR brings Laravel v10 support to Breeze.
I adjusted the install command to fail when it cannot resolve composer dependencies. Previously, this was lost in our CI build and it wasn't clear why Breeze couldn't be installed. Thanks to failing when composer dependencies cannot be resolved, I was able to find out Sanctum needed to be updated.

[1.x] Laravel v10

---

stubs/default/resources/views/layouts/navigation.blade.php
stubs/inertia-react/resources/js/Layouts/AuthenticatedLayout.jsx
stubs/inertia-vue/resources/js/Layouts/AuthenticatedLayout.vue

Currently the dark dropdown text is gray-500 compared to nav-links which have text of gray-400.
This PR aims to make the nav menu items consistent.
> Please include before / after screenshots.

Update nav menu dark text to be consistent with nav link

---

src/Console/InstallsBladeStack.php

It informs the user that we are installing node dependencies. It would justify the blank delay screen while installing node dependencies.
When we are installing the breeze scaffold there are **_delays in installing node dependencies_**. There is no indication some processes are running and the user may find lost as it seems to be stuck command. 
It would inform users that were installing node dependencies.

Inform user of dependency install process

---

stubs/api/routes/auth.php
stubs/default/routes/auth.php
stubs/inertia-common/routes/auth.php

Laravel added support for **[Single Action/Invokable Controller](https://laravel.com/docs/9.x/controllers#single-action-controllers)** since v5.6. According to the documentation:
> When registering routes for single action controllers, you do not need to specify a controller method. Instead, you may simply pass the name of the controller to the router
This PR cleans up the route files by removing the unnecessarily specified `__invoke` method for the __Single Action__ controllers. 
These changes should not cause any breaking changes.

[1.x] Clean up route definition for Single Action Controllers

---

src/Console/InstallCommand.php
src/Console/InstallsInertiaStacks.php

This pull request adjusts the install command, so Pest can be installed in Laravel 10.

[1.x] Supports Laravel 10 with `--pest`

---

stubs/default/resources/views/profile/partials/delete-user-form.blade.php

Just a small change that does same people some time that want to translate the placeholder for the password in the delete-user-form.blade.php

[1.x] Add translation to placeholder in delete-user-form.blade.php

---

stubs/default/resources/views/profile/partials/delete-user-form.blade.php

A very tiny little change that allows a possibly-forgotten string of text to be localized.
Changed an _x-input-label_ attribute `value="Password"` to `value="{{ __('Password') }}"`.

[1.x] Allowed a hardcoded string to be localized

---

stubs/inertia-react/resources/js/Pages/Auth/ForgotPassword.jsx

The email field in the ForgotPassword form is wrongly labels as "password". This PR changes the field Id to "email". Like on the other Auth forms.

[1.x] Fix input field Id in ForgotPassword.jsx

---

stubs/inertia-react/resources/js/Pages/Profile/Partials/DeleteUserForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdatePasswordForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx

Components that destructure the `className` prop need to specify a default empty string. Otherwise, if the consuming component does not provide a `className`, the value will be `undefined`. When the `className` is cast to a string in the template, JavaScript will insert a literal string `"undefined"` as a class name.

[1.x] React - Fix potential "undefined" class

---

stubs/inertia-react/resources/js/Pages/Auth/ConfirmPassword.jsx
stubs/inertia-react/resources/js/Pages/Auth/ForgotPassword.jsx
stubs/inertia-react/resources/js/Pages/Auth/Login.jsx
stubs/inertia-react/resources/js/Pages/Auth/Register.jsx
stubs/inertia-react/resources/js/Pages/Auth/ResetPassword.jsx

This PR removes the local `handleOnChange` functions and calls Inertia's `setData` method directly instead.
This usage matches the Inertia documentation at https://inertiajs.com/forms#form-helper.
It also matches the new TypeScript version at #267, which also removed this function to avoid an extra type definition.
I've also fixed the default value of the `remember` prop.

[1.x] React - Simplify Form Handler

---

stubs/inertia-react/resources/js/Components/TextInput.jsx

Fix ref in react TextInput

---

stubs/default/app/Http/Controllers/ProfileController.php
stubs/inertia-common/app/Http/Controllers/ProfileController.php

This PR aims to standardize the `current-password` rule in ProfileController utilizing the known `current_password` rule name.
While `current-password` still works as expected, the oficially documented rule is `current_password`, and since this files are published to the user application, it makes sense to use the common name.

Update `current_password` rule in ProfileController

---

src/Console/InstallsInertiaStacks.php

This PR fixes an issue in the Breezes installer where it would always install the PHPUnit version of `ProfileTest` and `PasswordUpdateTest` regardless of whether the `--pest` option was specified.
Thanks go to [this tweet](https://twitter.com/swazlo/status/1639623260852850689) for raising the issue.
I've also added a missing failure handler to the React stack installer for when Pest fails to be installed, which I noticed was present in the other stack installers.

[1.x] Fix Pest test installation for Inertia stack

---

stubs/inertia-vue-ts/resources/js/Pages/Auth/Register.vue
stubs/inertia-vue/resources/js/Pages/Auth/Register.vue

Remove redundant form data in vue stub

Remove redundant form data in vue stub

---

stubs/inertia-vue-ts/resources/js/Pages/Auth/ConfirmPassword.vue
stubs/inertia-vue-ts/resources/js/Pages/Auth/Login.vue
stubs/inertia-vue-ts/resources/js/Pages/Auth/Register.vue
stubs/inertia-vue-ts/resources/js/Pages/Auth/ResetPassword.vue
stubs/inertia-vue-ts/resources/js/Pages/Profile/Partials/DeleteUserForm.vue
stubs/inertia-vue-ts/resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue

Inertia Typescript doesn't allow it to call form methods implicitly on form event callbacks.
This is not allowed:
```ts
form.post(route('password.confirm'), {
onFinish: () => form.reset(),
});
```
(Typescript) error:
`Argument type {} & InertiaFormProps{} is not assignable to parameter type Partial<VisitOptions> | undefined`
Wrapped it with curly brackets:
```ts
form.post(route('password.confirm'), {
onFinish: () => {
form.reset();
},
});
```
More info is here: https://stackoverflow.com/q/76323706/17666912

[1.x] Remove implicit form method calls

---

stubs/default/resources/views/components/dropdown.blade.php
stubs/inertia-react-ts/resources/js/Components/Dropdown.tsx
stubs/inertia-react-ts/resources/js/Pages/Profile/Partials/UpdatePasswordForm.tsx
stubs/inertia-react-ts/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.tsx
stubs/inertia-react/resources/js/Components/Dropdown.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdatePasswordForm.jsx
stubs/inertia-react/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.jsx
stubs/inertia-vue-ts/resources/js/Components/Dropdown.vue
stubs/inertia-vue-ts/resources/js/Components/Modal.vue
stubs/inertia-vue-ts/resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue
stubs/inertia-vue-ts/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
stubs/inertia-vue/resources/js/Components/Dropdown.vue
stubs/inertia-vue/resources/js/Components/Modal.vue
stubs/inertia-vue/resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue
stubs/inertia-vue/resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue

We currently have a TS failure due to the Vue transition type not supporting the "class" attribute.
Migrated to the recommend attributes and also standardised the JSX version as well.
Vue Transition: https://vuejs.org/guide/built-ins/transition.html
Headless UI Transition: https://headlessui.com/react/transition
I've also remove the redundant `transform` class from transitions.

[1.x] Fix and standardise transitions

---

stubs/inertia-react-ts/resources/js/app.tsx
stubs/inertia-react-ts/resources/js/ssr.tsx
stubs/inertia-react/resources/js/app.jsx
stubs/inertia-react/resources/js/ssr.jsx
stubs/inertia-vue-ts/resources/js/app.ts
stubs/inertia-vue-ts/resources/js/ssr.ts
stubs/inertia-vue/resources/js/app.js
stubs/inertia-vue/resources/js/ssr.js

Currently, `appName` in app.tsx is pulled via DOM from app.blade.php <title> tag. It _works_, but using it from .env seems like a better approach. Additionally, it serves as an example of how .env variables should be accessed in React/Vue.
The `ssr` templates had `'Laravel'` hardcoded as the app name, which is not great for SEO. Replaced those parts with `import.meta.env.VITE_APP_NAME` as well.
This depends on https://github.com/laravel/laravel/pull/6204 where I added `VITE_APP_NAME` as an alias to `APP_NAME`
I don't think any changes in this PR could be considered breaking.
Similar issue fixed in Jetstream: https://github.com/laravel/jetstream/pull/1329

Use appName directly from .env in <title>

---

stubs/inertia-common/app/Http/Middleware/HandleInertiaRequests.php

IMO, this change makes it more readable. Performance should be the same or better.

[1.x] Replace `array_merge` with spread operator in `HandleInertiaRequests`

---

stubs/livewire/resources/views/livewire/pages/auth/verify-email.blade.php

Added class import to prevent `Class "RouteServiceProvider" not found` error.

Fix missing class import

---

stubs/api/app/Http/Controllers/Auth/RegisteredUserController.php
stubs/default/app/Http/Controllers/Auth/RegisteredUserController.php
stubs/default/app/Http/Requests/ProfileUpdateRequest.php
stubs/inertia-common/app/Http/Controllers/Auth/RegisteredUserController.php
stubs/livewire-functional/resources/views/livewire/pages/auth/register.blade.php
stubs/livewire-functional/resources/views/livewire/profile/update-profile-information-form.blade.php
stubs/livewire/resources/views/livewire/pages/auth/register.blade.php
stubs/livewire/resources/views/livewire/profile/update-profile-information-form.blade.php

This pull request ensures that the given user email is lowercase.
Tests are failing due: https://github.com/laravel/breeze/pull/320.

[1.x] Adds `lowercase` validation rule to user's `email` field

---

src/Console/InstallCommand.php

With the addition of the Livewire stacks, we now have more options that we do height in the prompts select viewport.
This is a very finite list and it feels weird to hide the one option. Proposing we expand it to show all available options.

[1.x] Don't hide options

---

stubs/livewire-functional/resources/views/livewire/pages/auth/login.blade.php
stubs/livewire/resources/views/livewire/pages/auth/login.blade.php

**Problem**:
After creating a new Laravel project with the Breeze Livewire starter kit, I noticed my `remember_token` would never be stored, meaning you'd never stay logged in.
After debugging it seems that for this specific flavour of templates there is a typo in the `login.blade.php`. The `$this->only` function in the call to `auth()->attempt()` get's closed after `$this->remember` instead of before, which means it's filtered out.

fix: Livewire 'remember me' flow for login doesn't remember

---

src/Console/InstallsLivewireStack.php
stubs/livewire-common/app/Livewire/Actions/Logout.php
stubs/livewire-common/app/Livewire/Forms/LoginForm.php
stubs/livewire-common/pest-tests/Feature/Auth/AuthenticationTest.php
stubs/livewire-common/tests/Feature/Auth/AuthenticationTest.php
stubs/livewire-functional/resources/views/livewire/layout/navigation.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/confirm-password.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/forgot-password.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/login.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/register.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/reset-password.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/verify-email.blade.php
stubs/livewire-functional/resources/views/livewire/profile/delete-user-form.blade.php
stubs/livewire-functional/resources/views/livewire/profile/update-password-form.blade.php
stubs/livewire-functional/resources/views/livewire/profile/update-profile-information-form.blade.php
stubs/livewire/resources/views/livewire/layout/navigation.blade.php
stubs/livewire/resources/views/livewire/pages/auth/confirm-password.blade.php
stubs/livewire/resources/views/livewire/pages/auth/forgot-password.blade.php
stubs/livewire/resources/views/livewire/pages/auth/login.blade.php
stubs/livewire/resources/views/livewire/pages/auth/register.blade.php
stubs/livewire/resources/views/livewire/pages/auth/reset-password.blade.php
stubs/livewire/resources/views/livewire/pages/auth/verify-email.blade.php
stubs/livewire/resources/views/livewire/profile/delete-user-form.blade.php
stubs/livewire/resources/views/livewire/profile/update-password-form.blade.php
stubs/livewire/resources/views/livewire/profile/update-profile-information-form.blade.php

Refactoring PR to clean up some code duplication in the Livewire stack as well as extract the complicated login logic into a Livewire Form. Also adds comments on class based stack.

Beautify Livewire Stack

---

stubs/inertia-react-ts/resources/js/Components/Modal.tsx

-  'ReactNode' is defined but never used

refactor: remove unused import

---

stubs/livewire/resources/views/livewire/layout/navigation.blade.php

`App\Livewire\Forms\LogoutForm;` doesn't exist and not being used anywhere. This PR removes the import statement `use App\Livewire\Forms\LogoutForm;` from Livewire stub file.

Remove unused import statement

---

stubs/default/resources/views/profile/partials/update-password-form.blade.php
stubs/livewire-functional/resources/views/livewire/profile/update-password-form.blade.php
stubs/livewire/resources/views/livewire/profile/update-password-form.blade.php

- When visiting the profile page Breeze generates, there are a couple of warnings in the DevTools related to multiple elements using the same ID (see screenshot). Since these inputs are all displayed in the same page, they must use different DOM IDs.
---
<details>
<summary>Screenshot</summary>
**before**
**after**
</details>

[1.x] Fix duplicate password fields

---

stubs/livewire-common/pest-tests/Feature/Auth/AuthenticationTest.php
stubs/livewire-common/pest-tests/Feature/Auth/RegistrationTest.php
stubs/livewire-common/pest-tests/Feature/ProfileTest.php
stubs/livewire-common/tests/Feature/Auth/AuthenticationTest.php
stubs/livewire-common/tests/Feature/Auth/RegistrationTest.php
stubs/livewire-common/tests/Feature/ProfileTest.php

`assertOK()` should be made before `assertSeeVolt()` and other assertions. If response is not ok and `assertOK` is not first, it can be difficult to debug (this has bitten me before).

asserting responses are ok before asserting presence of components

---

stubs/livewire-functional/resources/views/livewire/layout/navigation.blade.php
stubs/livewire/resources/views/livewire/layout/navigation.blade.php

This PR implements proper handling for names containing single quotes in the Livewire navigation component. The fix ensures that the names display correctly.
The current implementation fails to display names containing single quotes (e.g. Wellington O'Reilly) correctly within the navigation. This issue leads to an error in the browser console, triggering a `SyntaxError: missing } after property list` when such names are encountered.

Fix handling of names with single quotes in Livewire navigation

---

stubs/livewire-functional/resources/views/livewire/layout/navigation.blade.php
stubs/livewire/resources/views/livewire/layout/navigation.blade.php

This pull request uses `json_encode` while displaying the username on the navigation bar - avoiding issues when the user has quotes on his name.

[1.x] Uses `json_encode` like Jetstream

---

stubs/default/resources/views/components/modal.blade.php

Stumbled upon this issue in my project. Having this directive helped a ton. We could dispatch an event from the Livewire function (`$this->dispatch('close-modal', 'modal-name');`) so the modal can be closed after form submission. Hopefully, this helps others too.

Added a x-on:close-modal.window directive so we can close modal from a livewire function

---

src/Console/InstallsInertiaStacks.php
stubs/inertia-vue-ts/resources/js/Components/TextInput.vue
stubs/inertia-vue/resources/js/Components/TextInput.vue
stubs/inertia-vue/vite.config.js

https://blog.vuejs.org/posts/vue-3-3

[1.x] Switch to `defineModel` in Vue stubs

---

stubs/inertia-react-ts/resources/js/Pages/Profile/Partials/DeleteUserForm.tsx
stubs/inertia-react-ts/resources/js/Pages/Profile/Partials/UpdatePasswordForm.tsx

This fixes missing default values for `useRef` calls that use generics, in this case `HTMLInputElement`.
Currently the returned value is inferred as `HTMLInputElement | null | undefined`. Adding null as a default value is better, since the returned value is inferred as `HTMLInputElement | null` due to the signature `function useRef<T>(initialValue: T | null): RefObject<T>;`.
I ran into this issue because I swapped the `<TextInput />` in the `<UpdatePasswordForm />` component with a different input component (https://ui.shadcn.com/docs/components/input), which caused an error when passing the `ref` down to the new component. Adding null as the default value fixed that issue.

Add default value for useRef calls in .tsx files

---

src/Console/InstallsLivewireStack.php
stubs/livewire-functional/resources/views/livewire/pages/auth/confirm-password.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/login.blade.php
stubs/livewire-functional/resources/views/livewire/pages/auth/verify-email.blade.php
stubs/livewire-functional/resources/views/livewire/profile/update-profile-information-form.blade.php
stubs/livewire/resources/views/livewire/pages/auth/confirm-password.blade.php
stubs/livewire/resources/views/livewire/pages/auth/login.blade.php
stubs/livewire/resources/views/livewire/pages/auth/verify-email.blade.php
stubs/livewire/resources/views/livewire/profile/update-profile-information-form.blade.php

Since [Livewire 3.4](https://github.com/livewire/livewire/releases/tag/v3.4.0), the `redirectIntended` [function](https://livewire.laravel.com/docs/redirecting#redirect-to-intended) is available. This PR migrates the traditional redirects to this new function.

[1.x] Use Livewire's `redirectIntended` function

---

stubs/api/pest-tests/Feature/Auth/PasswordResetTest.php
stubs/api/tests/Feature/Auth/PasswordResetTest.php
stubs/default/pest-tests/Feature/Auth/PasswordResetTest.php
stubs/default/tests/Feature/Auth/PasswordResetTest.php

This PR improves tests that are delivered through fresh Breeze install.
Currently, a flaw is within `PasswordResetTest` -> `password can be reset with valid token` - it only checks for session error messages, while the `NewPasswordController` method `store` could be returning an internal error (HTTP code 500). 
Submitted changes adds a check for a successful return code which gives two things - there was no error in the controller logic and the resulting behaviour is in line with what is expected to happen.

Improve default auth tests inside the stubs

---

src/Console/InstallsInertiaStacks.php
stubs/inertia-react-ts/resources/js/ssr.tsx
stubs/inertia-react-ts/resources/js/types/global.d.ts
stubs/inertia-react/resources/js/ssr.jsx
stubs/inertia-vue-ts/resources/js/app.ts
stubs/inertia-vue-ts/resources/js/ssr.ts
stubs/inertia-vue-ts/resources/js/types/global.d.ts
stubs/inertia-vue/resources/js/app.js
stubs/inertia-vue/resources/js/ssr.js

[Ziggy v2 was just released](https://github.com/tighten/ziggy/releases/tag/v2.0.0), this PR updates Breeze accordingly. Corresponding Jetstream PR: https://github.com/laravel/jetstream/pull/1442.
These changes only affect Breeze's install command and stubs, so they shouldn't have any impact on existing apps scaffolded with Breeze.

Update to Ziggy v2

---

.gitignore
stubs/default/app/Http/Requests/Auth/LoginRequest.php

This is a simple fix that allows PHPStan level 9 to pass validation on this request file.
`Str::lower` expects the value given to be a string, however, `$this->input('email')` returns mixed, causes PHPStan to fail at level 9.
We can not cast the value to a string as an error is thrown when trying to cast a mixed object.
```php
(string) $this->input('email') // Causes an error
```
This does not cause any breaking changes and leverages the "Illuminate\Http\Concerns\InteractsWithInput" class.
Edit: Fixed a typo.

Updated throttleKey method to meet Str::lower excepted value in LoginRequest stub

---

stubs/livewire-common/app/Livewire/Forms/LoginForm.php
stubs/livewire-functional/resources/views/livewire/pages/auth/login.blade.php
stubs/livewire/resources/views/livewire/pages/auth/login.blade.php

Without the `form.` prefix, it won't show the actual validation errors (except the manual thrown `ValidationException`).

Fix Livewire form validation
